require('lv-globals')
vim.cmd('luafile ~/.config/nvim/lv-settings.lua')

require('settings')
require('keybindings')
require('plugins')

require('colorscheme')

require('lv-telescope')
require('lv-compe')
require('lv-treesitter')
require('lv-nvimtree')
require('lv-indent-blankline')
require('lv-gitsigns')
-- require('lv-dashboard')
require('lv-autopairs')
require('lv-comment')
require('lv-galaxyline')
-- require('lv-which-key')
require('lv-barbar')
-- require('lv-rnvimr')

require('lv-utils')
require('lv-autocommands')

-- TODO is there a way to do this without vimscript
vim.cmd('source ~/.config/nvim/vimscript/functions.vim')
vim.cmd('source ~/.config/nvim/vimscript/filetypes.vim')
vim.cmd('source ~/.config/nvim/vimscript/obsession.vim')
vim.cmd('source ~/.config/nvim/vimscript/startify.vim')

-- LSP
require('lsp')
require('lsp.angular-ls')
require('lsp.bash-ls')
require('lsp.clangd')
require('lsp.css-ls')
require('lsp.dart-ls')
require('lsp.docker-ls')
require('lsp.efm-general-ls')
require('lsp.elm-ls')
require('lsp.emmet-ls')
require('lsp.graphql-ls')
require('lsp.go-ls')
require('lsp.html-ls')
require('lsp.json-ls')
require('lsp.js-ts-ls')
require('lsp.kotlin-ls')
require('lsp.latex-ls')
require('lsp.lua-ls')
require('lsp.php-ls')
require('lsp.python-ls')
require('lsp.ruby-ls')
require('lsp.rust-ls')
require('lsp.svelte-ls')
require('lsp.terraform-ls')
-- require('lsp.tailwindcss-ls')
require('lsp.vim-ls')
require('lsp.vue-ls')
require('lsp.yaml-ls')
-- require('lsp.elixir-ls')
