-- local utils = require('utils')

-- local auto_formatters = {            }

-- local python_autoformat = {'BufWritePre', '*.py', 'lua vim.lsp.buf.formatting_sync(nil, 1000)'}
-- if Globals.python.autoformat then table.insert(auto_formatters, python_autoformat) end

-- local javascript_autoformat = {'BufWritePre', '*.js', 'lua vim.lsp.buf.formatting_sync(nil, 1000)'}
-- local javascriptreact_autoformat = {'BufWritePre', '*.jsx', 'lua vim.lsp.buf.formatting_sync(nil, 1000)'}
-- local typescript_autoformat = {'BufWritePre', '*.ts', 'lua vim.lsp.buf.formatting_sync(nil, 1000)'}
-- local typescriptreact_autoformat = {'BufWritePre', '*.tsx', 'lua vim.lsp.buf.formatting_sync(nil, 1000)'}
-- if Globals.tsserver.autoformat then
--     table.insert(auto_formatters, javascript_autoformat)
--     table.insert(auto_formatters, javascriptreact_autoformat)
--     table.insert(auto_formatters, typescript_autoformat)
--     table.insert(auto_formatters, typescriptreact_autoformat)
-- end

-- local lua_format = {'BufWritePre', '*.lua', 'lua vim.lsp.buf.formatting_sync(nil, 1000)'}
-- if Globals.lua.autoformat then table.insert(auto_formatters, lua_format) end

-- local json_format = {'BufWritePre', '*.json', 'lua vim.lsp.buf.formatting_sync(nil, 1000)'}
-- if Globals.json.autoformat then table.insert(auto_formatters, json_format) end

-- local ruby_format = {'BufWritePre', '*.rb', 'lua vim.lsp.buf.formatting_sync(nil,1000)'}
-- if Globals.ruby.autoformat then table.insert(auto_formatters, ruby_format) end

-- utils.define_augroups({
--     _general_settings = {
--         {'TextYankPost', '*', 'lua require(\'vim.highlight\').on_yank({higroup = \'Search\', timeout = 200})'},
--         {'BufWinEnter', '*', 'setlocal formatoptions-=c formatoptions-=r formatoptions-=o'},
--         {'BufRead', '*', 'setlocal formatoptions-=c formatoptions-=r formatoptions-=o'},
--         {'BufNewFile', '*', 'setlocal formatoptions-=c formatoptions-=r formatoptions-=o'},
--         {'VimLeavePre', '*', 'set title set titleold='}

--         -- {'User', 'GoyoLeave', 'lua require(\'galaxyline\').disable_galaxyline()'},
--         -- {'User', 'GoyoEnter', 'lua require(\'galaxyline\').galaxyline_augroup()'},
--     },
--     _blankline = {
--         {'CursorMoved', '*', 'silent! IndentBlanklineRefresh'},
--     },
--     -- _java = {
--     --     {'FileType', 'java', 'luafile ~/.config/nvim/lua/lsp/java-ls.lua'},
--     --     {'FileType', 'java', 'nnoremap ca <Cmd>lua require(\'jdtls\').code_action()<CR>'}
--     -- },
--     _dashboard = {
--         -- seems to be nobuflisted that makes my stuff disapear will do more testing
--         {
--             'FileType', 'dashboard',
--             'setlocal nocursorline noswapfile synmaxcol& signcolumn=no norelativenumber nocursorcolumn nospell  nolist  nonumber bufhidden=wipe colorcolumn= foldcolumn=0 matchpairs= '
--         },
--         {
--             'FileType', 'dashboard', 'set showtabline=0 | autocmd BufLeave <buffer> set showtabline=2'
--         }
--     },
--     _markdown = {{'FileType', 'markdown', 'setlocal wrap'}, {'FileType', 'markdown', 'setlocal spell'}},
--     _solidity = {
--         {'BufWinEnter', '.sol', 'setlocal filetype=solidity'}, {'BufRead', '*.sol', 'setlocal filetype=solidity'},
--         {'BufNewFile', '*.sol', 'setlocal filetype=solidity'}
--     },
--     _gemini = {
--         {'BufWinEnter', '.gmi', 'setlocal filetype=markdown'}, {'BufRead', '*.gmi', 'setlocal filetype=markdown'},
--         {'BufNewFile', '*.gmi', 'setlocal filetype=markdown'}
--     },
--     _graphql = {
--         {'BufRead', '*.gql', 'setfiletype graphql'}, {'BufNewFile', '*.gql', 'setfiletype graphql'},
--         {'BufRead', '*.graphql', 'setfiletype graphql'}, {'BufNewFile', '*.graphql', 'setfiletype graphql'}
--     },
--     _blade = {
--         {'BufRead', '*.blade.php', 'setfiletype blade'}, {'BufNewFile', '*.blade.php', 'setfiletype blade'},
--     },
--     _env = {
--         {'BufRead', '*.env.*', 'setfiletype sh'}, {'BufNewFile', '*.env.*', 'setfiletype sh'},
--     },
--     _tmux = {
--         {'BufRead', 'tmux*.conf', 'setfiletype tmux'}, {'BufNewFile', '.tmux*.conf', 'setfiletype tmux'},
--         {'BufRead', 'tmux*.conf.*', 'setfiletype tmux'}, {'BufNewFile', '.tmux*.conf.*', 'setfiletype tmux'},
--     },
--     _buffer_bindings = {
--         {'FileType', 'dashboard', 'nnoremap <silent> <buffer> q :q<CR>'},
--         {'FileType', 'lspinfo', 'nnoremap <silent> <buffer> q :q<CR>'},
--         {'FileType', 'floaterm', 'nnoremap <silent> <buffer> q :q<CR>'},
--         {'FileType', 'startify', 'setlocal nowrap'},
--     },
--     _auto_formatters = auto_formatters
-- })
